### PR TITLE
Add Style.ci config file

### PR DESCRIPTION
**Pull request by luizpedone**

### CODE REVIEW

**Comment by luizpedone** [comment]
@jgrossi: The StyleCI implementation is OK. I'll do the Travis CI integration soon.

**Comment by jgrossi** [comment]
Thanks @luizpedone! Any question just let me know. Best...

**Comment by jgrossi** [comment]
Awesome @luizpedone! Thanks a lot

**Comment by jgrossi** [comment]
Fixing #135

**Pull request merged**
