### PR TITLE
Update REAMDE with Capitalize P for WordPress

### PR DESCRIPTION
**Pull request by leocaseiro**
Same as #87 for Readme

### CODE REVIEW

**Comment by jgrossi** [comment]
Man sorry! I have to revert your PR. Please, make it in the `dev` branch, not `master`. The `dev` has information `master` does not. Please, send your PR again :-)

**Comment by jgrossi** [comment]
Actually, I had these changes some minutes ago. But I can revert my change to merge your PR. I'm gonna do this and you update your dev branch and send the PR, ok?

**Comment by leocaseiro** [comment]
No worries, I'll update the dev branch and send a new PR

**Comment by jgrossi** [comment]
Wait to me revert the changes I've made and I contact you here to send your PR.

**Comment by leocaseiro** [comment]
No problem! :+1: :beers:

**Comment by jgrossi** [comment]
Ok @leocaseiro! Now you can send the PR :-)

**Comment by jgrossi** [comment]
@leocaseiro agora que tô vendo que vc também é brazuca hahahaha

**Comment by leocaseiro** [comment]
É nóis!!! Vi seu projeto na newsletter [A Semana PHP#73](http://www.asemanaphp.com.br/edicoes/edicao73.html)

**Pull request merged**
