### PR TITLE
Added meta filter scope

### PR DESCRIPTION
**Pull request by Dreanmer**
If you use ACF, you can't live without this feature;

### CODE REVIEW

**Comment by jgrossi** [comment]
Hi @Dreanmer! First thanks for the contribution. 

About your PR, you've added a meta scope used by Eloquent, but why? I think using this you can use a method called `meta()` to get custom fields but this feature already exists. Maybe you can merge this Laravel way using scope with `__get` magic method. 

Currently to get custom fields - even using ACF - you can use `$post->meta->field` or `$post->field`. We can create both ways, using vars and method but using the same code.

What do you think about? Thanks for the support.

**Comment by jgrossi** [comment]
@Dreanmer and please, send the PR to the `dev` branch :-) Thanks again and continue the great support ;-)

**Comment by Dreanmer** [comment]
sorry i messed the branch, this feature isn't for getting a meta, its for filter posts that have the meta or the value... like i said, if you use ACF u understand better... eg.: i have many pages who have a custom field 'xxx' and want to filter then... other than Page::all() then loop this, i filter direct on query... sorry bad english i cant explain better.

**Comment by jgrossi** [comment]
Ok! Nice ;-) just add about `$post->hasMeta` on the README file, please :D

**Comment by Dreanmer** [comment]
i'll do it, then reopen on dev branch

**Comment by jgrossi** [comment]
That's nice! If you want just send the PR to dev branch and I can insert the instructions on README file. :-)

**Pull request closed without merging**
