### PR TITLE
a package went missing.

### PR DESCRIPTION
**Pull request by castillo-n**
the update points "hautelook/phpass": "0.3.*",: to castillo/phpass:"0.3" which is just a clone from the original phpass. You can as well just clone my cloned repo if you like and discard this pull request. 
Thank you for your time!

### CODE REVIEW

**Comment by jgrossi** [comment]
hey @castillo-n is there any reason why you cloned the phpass repo?

**Comment by kharysharpe** [comment]
Hi @jgrossi 

Looks like they either deleted the repo or made it private, hence why he cloned it.

It's preventing deployment of applications that use corcel.

Error Message:

```
- Installing hautelook/phpass (0.3.5): Downloading (connecting...)Downloading (failed)           Failed to download hautelook/phpass from dist: The "https://api.github.com/repos/hautelook/phpass/zipball/b4cbd9b67ed3ef5672ec79d8e0c46d24bd844abd" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing hautelook/phpass (0.3.5): Cloning b4cbd9b67e

                                                                                                      
  [RuntimeException]                                                                                  
  Failed to clone https://github.com/hautelook/phpass.git via https, ssh protocols, aborting.         
                                                                                                      
  - https://github.com/hautelook/phpass.git                                                           
    Cloning into '/home/...../releases/20210912145708/vendor/hautelook/phpass'...  
    remote: Invalid username or password.                                                             
    fatal: Authentication failed for 'https://github.com/hautelook/phpass.git/'                       
                                                                                                      
  - git@github.com:hautelook/phpass.git                                                               
    Cloning into '/home/..../releases/20210912145708/vendor/hautelook/phpass'...  
    git@github.com: Permission denied (publickey).                                                    
    fatal: Could not read from remote repository.                                                     
                                                                                                      
    Please make sure you have the correct access rights                                               
    and the repository exists.                         
```

See also #574

**Comment by castillo-n** [comment]
Hi @jgrossi, @kharysharpe is right, the only reason I cloned it was to make sure I have a saved copy of it, I am not deleting it as many old projects I have worked on it, use it. Also I use your package a lot so I was hoping to help. If you want to close the pull request and just clone my clone, go for it. I am fine with whatever works best. Thanks for all the work you have put in into this project!

**Comment by jgrossi** [comment]
thanks for the feedback folks, really appreciate that.

we have another option that @TheoKouzelis added here #576. we might not need that package anymore, but we might have the secrets invalidated in the database :-(

is there any official replacement for the removed package or nothing yet?

**Comment by jgrossi** [comment]
hey again. I had to do some changes once we were not running tests on PRs. I've moved from travis-ci to github actions and moved the phpass to `bordoni/phpass` for now (`v5.1.0`)

I will apply soon the change suggested by @TheoKouzelis and remove phpass once and for all as a dependency.

thanks for the heads up folks 🥇

**Pull request closed without merging**
