### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by redbeed**

### CODE REVIEW

**Comment by jgrossi** [comment]
Hi @redbeed! Some updates were made into Corcel to work with both L4 and L5. What is different in your fork that is not covered by Corcel? Thanks

**Comment by redbeed** [comment]
You can easily use it with Laravel 5. 
After "artisan publish" you can write the name of your database connection for corcel into the corcel.php file.
In your original repo. you overwrite the default database connection, with my fork everything in laravel is work fine and you can see the query of the corcel package in the "laravel debugbar" because an laravel database connection is used.

**Comment by jgrossi** [comment]
Ok @redbeed  very nice job. But I think is better to include the good improvements we've made inside Corcel repository, not another one. ;-)

**Comment by redbeed** [comment]
Yes @jgrossi but i overwrite many file and or remove unused think like "newquery" functions

**Comment by jgrossi** [comment]
Ok @redbeed so would be better to pull request all the changes you've made to Corcel's master repo to be exclusive for L5 and create another branch just for L4. To use Corcel for L4 just clone the L4 branch and for L5 the master branch. So, after that, the master branch will be L5 only by now.

What do you think about that?

**Pull request closed without merging**
