### PR TITLE
Laravel 6.0 support

### PR DESCRIPTION
**Pull request by roelofr**
Add support for Laravel 6.0 and up.

### CODE REVIEW

**Comment by roelofr** [comment]
Okay, the codebase is updated.

I updated all Illuminate dependencies to `^6.0`, updated workbench and took the liberty of prepping the unit tests for PHPUnit 9 (which introduces a bunch of removals)

**Comment by roelofr** [comment]
Somehow locally the `str_random` functions still worked, even on a clean (containerized) build. Anyhow, replacing `str_random` with `Str::random` solved the issue.

:heavy_check_mark: Ready to be merged from my end.

**Comment by jgrossi** [comment]
@roelofr ready to be merged. created the 3.0 branch and changed the base one on your PR. 
just would like to ask you to update also the README file adding the necessary info about the new version (basically the table of compatibility, I think).

**Comment by roelofr** [comment]
Fair point. I added the new version number, and made sure to indicate it's for 3.0 and up (`^3.0`)

**Comment by roelofr** [comment]
I accidentally used `~2.1.x` instead of `~2.1.0` in the readme, which isn't a valid version number for Composer.

**Comment by ClaraLeigh** [comment]
Awesome, just came looking for this. 
This is the last thing in my list before I can update to laravel 6

**Comment by jgrossi** [comment]
thanks for that! 🙏

**Comment by jgrossi** [comment]
tagged `v3.0.0` with Laravel 6 support 🍾

**Pull request merged**
