### PR TITLE
Allow alternate Shortcode Parsers.

### PR DESCRIPTION
**Pull request by bluehaoran**
As per #428, this pull request allows an end-user to provide an alternate shortcode parser.

### CODE REVIEW

**Comment by jgrossi** [comment]
@bluehaoran got the idea, and it seems to be a very good addition, BTW. the only concern here is because Corcel is not **only** for Laravel users, so we might think some way to avoid that and making this customizable via the `ShortcodeFacade` class itself.

**Comment by bluehaoran** [comment]
Good use of `tap()`! (I always forget it exists.)

**Comment by jgrossi** [comment]
@bluehaoran can you add the documentation about changing the parser? 😉

**Comment by bluehaoran** [comment]
Documented, as requested!

**Comment by jgrossi** [comment]
@bluehaoran sounds good! just added two test cases to cover the Laravel/non-Laravel apps, when changing the parser. It seems to be working fine. tomorrow morning gonna take a last look and merge it! good job! 💪

**Comment by jgrossi** [comment]
@bluehaoran just made some improvements to these last tests I created. take a look before I merge it. thanks for the hard job 😎

**Comment by jgrossi** [comment]
@bluehaoran give me your twitter handle to mention you about these last updates 😉👏 if you want to ping me there, mine is `@junior_grossi` 💪

**Comment by bluehaoran** [comment]
No worries! Happy to help.

My Twitter handle is @thehaoran

**Pull request merged**
