### PR TITLE
support Laravel 11

### PR DESCRIPTION
**Pull request by atmonshi**

### CODE REVIEW

**Review by mfeldheim — CHANGES_REQUESTED** [review]
The Authenticatable interface has changed, the User model needs to implement that for Laravel 11

https://laravel.com/api/master/Illuminate/Auth/Authenticatable.html#method_getAuthPasswordName


```
/**
 * Get the name of the password attribute for the user.
 *
 * @return string
 */
public function getAuthPasswordName()
{
    return 'user_pass';
}

 /**
 * Get the password for the user.
 *
 * @return string
 */
public function getAuthPassword()
{
    $authPasswordName = $this->getAuthPasswordName();

    return $this->{$authPasswordName};
}

```

**Comment by atmonshi** [comment]
hey @jgrossi any update on this :)?

**Comment by jgrossi** [comment]
hey! PR merged and `v8.0.0` tagged with support to laravel 11. thanks all for the contributions

**Comment by dangnhdev** [comment]
Many thanks @jgrossi 🔥

**Pull request merged**
