### PR TITLE
Add Code Climate integration

### PR DESCRIPTION
**Pull request by luizpedone**
I've noticed that the Coveralls integration was not working, so I decided to add a Code Climate integration. The Code Climate is a very cool tool, showing test coverage reports over time and also code smells and an estimated maintainability effort.

In order to have it working, you have to allow Code Climate to access this repo and add the application key that Code Climate provides to the Travis CI. I can help with that if you guys need. :)

### CODE REVIEW

**Comment by jgrossi** [comment]
Hey @luizpedone ;-) thanks for contributing! I already enabled Code Climate for the `corcel/corcel` repo. Just a:

```
env:
  global:
    - CC_TEST_REPORTER_ID=[hash]
```

inside `travis.yml` is enough? Thanks!

**Comment by luizpedone** [comment]
@jgrossi I think it's not a good practice to version control the CC_TEST_REPORTER_ID. I'd rather store this as an environment variable inside Travis CI.

I've done this for my fork and looked something like this:

screen shot 2017-11-06 at 10 18 44

**Comment by jgrossi** [comment]
Nice, but is `CODECLIMATE_REPO_TOKEN` the default var name? Is there any config in Travis to make sure that new env var is going to be used?

**Comment by luizpedone** [comment]
@jgrossi Yes, that's all I used to get it working on my fork. :)

**Pull request merged**
