### PR TITLE
add filter by post parent ID

### PR DESCRIPTION
**Pull request by EazyServer**
Can you please accept this PR. I needed to filter by parent ID and could not find this on your package!
Thanks

### CODE REVIEW

**Comment by jgrossi** [comment]
@EazyServer I don't know why but I cannot change the base branch from `master` to `2.6`. can you try that please? thanks!

**Comment by EazyServer** [comment]
Hi

Not sure what you mean! Usually I PR to master and package maintainer test the integration on master and create a new release of master if integration (and/or tests) are successful.

If you have a different way please let me know and will be happy to resubmit my PR 👍

Thanks

**Comment by EazyServer** [comment]
Hi @jgrossi 
Any chance you can push this please? 
Thanks

**Comment by jgrossi** [comment]
Hi @EazyServer the `master` branch is not the main one. Corcel works with branches like Laravel does. The current main branch is `2.6` to follow Laravel 5.6 version. I updated the merge branch to `2.6` and gonna merge.

**Comment by EazyServer** [comment]
Thanks very much

**Pull request merged**
