### PR TITLE
Laravel 5.8 support

### PR DESCRIPTION
**Pull request by ChrisThompsonTLDR**

### CODE REVIEW

**Comment by jpmaga** [comment]
Wouldn't it be better to change it to "^5.7" instead of "5.8.x"? I think the biggest change for this package would be the deprecated helpers, but updating those should make it compatible with both versions. I am using it already on 5.8 without any issue, though.

**Comment by jgrossi** [comment]
@ChrisThompsonTLDR thanks for the PR... gonna merge it ASAP.. probably tomorrow gonna create a 2.8 branch to match 5.8 in Laravel and then I merge this PR! thanks!

**Comment by OwenMelbz** [comment]
Hey all!

Does anybody know if there was any movement on this? We're updating our apps to 5.8 and Corcel is the last package :D

**Comment by TechnicallyGio** [comment]
Any idea when you plan to merge this in? Kinda need to go up to 5.8

**Comment by jgrossi** [comment]
merged on `v2.8.0` 🙏

**Comment by anhskohbo** [comment]
@jgrossi could you please force update in the packagist, it's still not updated yet.

**Comment by jgrossi** [comment]
@anhskohbo done!

**Pull request merged**
