### PR TITLE
Corcel 5.0 with Laravel 8

### LINKED ISSUE #529: Not working with Laravel 8
- Corcel Version: 4.0.1
- Framework Name & Version: Laravel 8
- PHP Version: 7.3

### Description:
This package seems not to be working with Laravel 8.

Problem 1
    - Conclusion: don't install jgrossi/corcel v4.0.1
    - Conclusion: don't install jgrossi/corcel v4.0.0
    - Conclusion: remove laravel/framework 8.x-dev
    - Installation request for jgrossi/corcel ^4.0 -> satisfiable by jgrossi/corcel[4.0.x-dev, v4.0.0, v4.0.1].
    - Conclusion: don't install laravel/framework 8.x-dev
    - jgrossi/corcel 4.0.x-dev requires illuminate/database ^7.0 -> satisfiable by laravel/framework[7.x-dev], illuminate/database[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - Can only install one of: laravel/framework[7.x-dev, 8.x-dev].
    - don't install illuminate/database 7.x-dev|don't install laravel/framework 8.x-dev

### Steps To Reproduce:
composer require jgrossi/corcel

### PR DESCRIPTION
**Pull request by Jubeki**
Fixes #529 and allows Corcel to be installed or upgraded to a Laravel 8 application

- [x]  Upgrade packages
    - [x] Illuminate 8.x
    - [x] Orchestra Testbench 6.x
- [x]  Install Laravel Factory Legacy
- [x] Remove php 7.2 support
- [ ] Are Tests working?
- [ ] Create 5.0 branch @jgrossi

### CODE REVIEW

**Comment by bumbummen99** [comment]
@Jubeki You can fix the failing test by adding PostTest.php#284:
```php
Paginator::useBootstrap();
```
See the [L8 Upgrade Guide](https://laravel.com/docs/8.x/upgrade#pagination-defaults). We should also add a test for the Tailwind and Bootstrap 3 ones.

**Comment by Jubeki** [comment]
I don't see any Travis tests running, so I don't know if all tests are running/completed.
I only see StyleCI and CodeClimate. Am I missing something? Normally Travis would also be shown in the checks

**Comment by bumbummen99** [comment]
@Jubeki Yeah i think the link is broken, the repository owner could try to re-link the repo in hope to fix it.
Alternatively you can look [here](https://travis-ci.org/github/corcel/corcel/pull_requests) or run the tests manually by running  
`composer install && ./vendor/bin/phpunit`

**Comment by Jubeki** [comment]
@jgrossi Do you have time to review the pull request?

**Comment by Jubeki** [comment]
Maybe somebody else from the Corcel-PHP Team can take a look at this PR @adrianogl @rundef

**Comment by asjsrep** [comment]
Has this project been abandoned?

**Comment by squatto** [comment]
I'm beginning to wonder that myself...

**Comment by jgrossi** [comment]
`v5.0.0` tagged 👍 thanks @Jubeki and @bumbummen99 for the work 🙏

**Comment by squatto** [comment]
Thanks @jgrossi, @Jubeki, and @bumbummen99!!

**Pull request merged**
