### PR TITLE
Updated scopeHasMeta for Laravel 5.3 compatibility

### PR DESCRIPTION
**Pull request by Bartjuh4**

### CODE REVIEW

**Comment by jgrossi** [comment]
Hi @Bartjuh4 thanks for your efforts! Is it possible to add a test case to your branch? I'd like to test this new `hasMeta()` but it's impossible without a test case. Thanks again. Looking forward to see the test case added and the PR approved! Cheers, JG.

**Comment by Bartjuh4** [comment]
Hi @jgrossi, Sure sorry about that. Forgot to add testcase. I will look at this tonight

**Comment by Bartjuh4** [comment]
Hi @jgrossi, i added the test but i don't know how to add a test for 2 Laravel versions. I lowered the Laravel version in the lock file but there must be a better and easier way

**Comment by jgrossi** [comment]
@Bartjuh4 Thanks for contributing. 

The next releases of Corcel will only support Laravel from 5.3, don't worry with that.
Can you check the PHP code style? `styleci` is not passing. Check it out https://styleci.io/analyses/8Qe11g. 

Cheers, JG.

**Comment by Bartjuh4** [comment]
Hi @jgrossi, Sorry did not see that the style analysis was failing. I fixed the problem.

**Comment by jgrossi** [comment]
Thanks for contributing :-)

**Pull request merged**
