### PR TITLE
Update phpass vendor

### PR DESCRIPTION
**Pull request by samuelrojasp**
Need this change to be able to give support to a legacy project.

### CODE REVIEW

**Review by jclaren — APPROVED** [review]

**Comment by jgrossi** [comment]
hey thanks for the PR. in order to get it working as expected you also need to run composer update to update the lock file as well

**Comment by samuelrojasp** [comment]
> hey thanks for the PR. in order to get it working as expected you also need to run composer update to update the lock file as well

Thanks @jgrossi you're absolutely right. I had to update orchestra/testbench and orchestra/database to be able to run it since those needed illuminate/database 5.7 and the current one is 5.8.

**Comment by jgrossi** [comment]
so all tests passing for 2.8 branch? once we don't have GitHub actions in that branch could you please check manually?

**Comment by jgrossi** [comment]
tests passing 👍 merged and tagged as `v2.8.1`
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

...............................................................  63 / 170 ( 37%)
............................................................... 126 / 170 ( 74%)
............................................                    170 / 170 (100%)

Time: 25.19 seconds, Memory: 30.00 MB

OK (170 tests, 380 assertions)

```

**Pull request merged**
