### PR TITLE
Compatibility with laravel 10

### PR DESCRIPTION
**Pull request by Zubairsoft**

### CODE REVIEW

**Comment by p3dro-docplanner** [comment]
Hi @Zubairsoft! Do you know when this PR will be merged? Thanks!!

**Comment by diphuda** [comment]
> _ No description provided. _

How can I use this for my Laravel 10 project?

**Comment by aon4o** [comment]
Please, can this be merged?

**Comment by XenBG** [comment]
+1

**Comment by kossa** [comment]
Can anyone fork the project and merge this PR?

**Comment by jgrossi** [comment]
relates to https://github.com/corcel/corcel/pull/638

**Pull request merged**
