### PR TITLE
[3.0] Remove missing phpass in favour of Laravel support hash

### PR DESCRIPTION
**Pull request by TheoKouzelis**
Phpass has been deleted. But upon investigating the package, it seems it's main purpose is to support strong hasing in php versions less than 5.5 https://www.openwall.com/phpass/. Since this package requiresphp 7.2. I don't think the dependency is required.

**This will invalidate existing hashes stored in a database.**

### CODE REVIEW

**Comment by tshafer** [comment]
Yes please.

**Comment by boktoso** [comment]
+1

**Comment by georgi-vdimitrov** [comment]
+1

**Comment by XenBG** [comment]
+1

**Comment by mlg1** [comment]
+1

**Comment by TheoKouzelis** [comment]
Seems like this has been resolved by replacing hautelook/phpass with bordoni/phpass

**Pull request closed without merging**
