### PR TITLE
Add hasMeta scope feature and examples

### PR DESCRIPTION
**Pull request by Dreanmer**
Filter Posts having a specific meta/field.

### CODE REVIEW

**Comment by Dreanmer** [comment]
can't understand why it conflicted, BTW i added example on readme and some changes to user your way to get the DB connection

**Comment by jgrossi** [comment]
I'm gonna clone your branch and check that @Dreanmer. Give me a second.

**Comment by jgrossi** [comment]
@Dreanmer conflits fixed and PR merged :-) Welcome!

**Comment by Dreanmer** [comment]
thanks, i'm working on a bunch of features, some w'll not be useful for the community but some i'll commit when done.

**Comment by jgrossi** [comment]
Very nice @Dreanmer! Just send the PRs :-) Cheers!

**Pull request merged**
