### PR TITLE
support laravel 9

### PR DESCRIPTION
**Pull request by atmonshi**
support laravel 9

### CODE REVIEW

**Comment by bumbummen99** [comment]
Why a major version? Afaik this is not a BC

**Comment by atmonshi** [comment]
sorry I didn’t get it?

usually corcel will be relased on new version for every laravel major version

**Comment by wontone18** [comment]
> Why a major version? Afaik this is not a BC

its not working with laravel 9.0. You should b update your composer.

**Comment by bumbummen99** [comment]
> > Why a major version? Afaik this is not a BC
> 
> its not working with laravel 9.0. You should b update your composer.

Yes because the composer.json does clearly state "^8.0". It does seem you did not get what i actually mean. There is no breaking change between L8 & L9, that does mean a patch version (Major.Minor.Patch) would suffice since none of the code but only the max accepted version actually changed.

> sorry I didn’t get it?
> 
> usually corcel will be relased on new version for every laravel major version

Seems like it, sorry. Is there a reason why this is not semver @jgrossi?

**Comment by bumbummen99** [comment]
@atmonshi You also need to upgrade testbench to 7 for L9

**Review by jgrossi — APPROVED** [review]
thanks for contributing 🙏

**Comment by jgrossi** [comment]
released under new tag `v6.0.0` 👍

**Pull request merged**
