### PR TITLE
Bugfix for issue#77

### PR DESCRIPTION
**Pull request by rundef**
This is the bugfix for issue #77 
@jgrossi, I think we should create a CorcelModel which redefines the belongsTo/belongsToMany/hasMany, etc... functions to pass the DB connection along, and all our models can extend that class. What do you think ?

### CODE REVIEW

**Comment by jgrossi** [comment]
Thanks @rundef!

**Comment by jgrossi** [comment]
@rundef let me check some parts of the code and tell you.. but the idea of have a default model is great! these relation problems can be solved by that! give me some hours to make some tests and I contact you again, ok? thanks again for the awesome support :D

**Comment by jgrossi** [comment]
@rundef let's create a `Corcel\Model` class, where we'll set all information about relationships and all Corcel model classes will extend it... so users should create their own `Post` class extending `Corcel\Model` and not `Corcel\Post`.

Maybe this can be a easier solution in relationship instead of set all connections in relationships: http://laravel.io/forum/02-12-2014-many-to-many-relationship-not-working-across-databases

**Comment by rundef** [comment]
Yes that's a good idea. But if `Corcel\Post` extends `Corcel\Model` it's okay if the users extends `Corcel\Post` :)

**Comment by jgrossi** [comment]
Yep :-)

**Pull request merged**
