### PR TITLE
Submit requested PR from #106 that implements #69

### PR DESCRIPTION
**Pull request by lancepioch**
See #106 comment for details. You should use the merge and squash.

### CODE REVIEW

**Comment by jgrossi** [comment]
Hi @lancepioch can you update me again about this PR?

**Comment by lancepioch** [comment]
@kriskbx submitted a PR #106 to the master branch and you asked him to resubmit it to the dev branch. He hadn't responded for a while, so I did it for him.

**Comment by jgrossi** [comment]
Hummmm ok thanks @lancepioch. I'm gonna check that. Cheers!

**Comment by jgrossi** [comment]
I'm not understanding how we have 8 commits and only 1 file change! Weird! Hehehehe

**Comment by lancepioch** [comment]
He merged your new (upstream) committed branch with his which then shows you that those commits **will** be included and not discarded since the original pull request.

**Pull request merged**
