### PR TITLE
Options model

### PR DESCRIPTION
**Pull request by josec89**
```
PHPUnit 4.2.2 by Sebastian Bergmann.

Configuration read from /home/vagrant/projects/corcel/phpunit.xml

...........................

Time: 427 ms, Memory: 10.00Mb

OK (27 tests, 226 assertions)
```

- `phpunit.xml` file added so as to ease the testing process
- Options model added with static methods to get options by name or get all
- Options tests

### CODE REVIEW

**Comment by jgrossi** [comment]
Nice job @josec89 :-)

**Comment by rundef** [comment]
Nice job indeed!  I like it

**Comment by josec89** [comment]
Thanks, and thank you for creating this awesome package :)

**Comment by jgrossi** [comment]
Thanks @josec89! You're welcome!

**Comment by thiagof** [comment]
cant wait to use this one!

**Pull request merged**
