### PR TITLE
Add the "has meta" query condition.

### PR DESCRIPTION
**Pull request by erickmcarvalho**
Hi guys!

I added the `hasMeta` method in `UserBuild` because resulted in error getting the user logged in by remember token.
This simply adds nested `whereHas` by meta relationship, for verify if it exists.

Example:
```php
$this->createModel()->newQuery()
    ->whereId($identifier)
    ->hasMeta('remember_token', $token)
    ->first()
;
```

Like this:
```php
$this->createModel()->newQuery()
    ->whereId($identifier)
    ->whereHas('meta', function($query) use($token) {
        $query->where('meta_key', 'remember_token')
            ->where('meta_value', $token)
        ;
    })
    ->first()
;
```

If you have better solution, ignore this please! :smiley:
Thanks!

Sorry for bad english :confused:

### CODE REVIEW

**Comment by rundef** [comment]
Hi,

Thanks for the PR. 
Could you only add the second where condition only if metaValue is not `null` ?

Also, could you write a quick unit test for this method ?

I'll merge it afterwards.

Thanks

**Comment by erickmcarvalho** [comment]
Hi,

The idea is mainly fix the following error:
```
BadMethodCallException in Builder.php line 2405:
Call to undefined method **Illuminate\Database\Query\Builder::hasMeta()**
``` 

This presents to return in the application using remember token.
About the unit test, I think I can write yes, if necessary.

Thanks!

**Comment by rundef** [comment]
I realized that "hasMeta" has already been implemented.

I think this is [what you're looking for](https://github.com/jgrossi/corcel/blob/master/src/Providers/AuthUserProvider.php#L42)

**Comment by jgrossi** [comment]
Hi @erickmcarvalho! Thanks for contributing with Corcel. Please send you PR again to the `dev` branch. I'm gonna close this one. Thanks.

**Pull request closed without merging**
