### PR TITLE
starting to write test for Page->toArray()

### PR DESCRIPTION
**Pull request by manogi**
@jgrossi I think something goes wrong when I call toArray on my $page result. I started unit testing this, and right away the same error messages started again:

```
There was 1 error:

1) TaxonomyTest::testPageToArray
Undefined property: Page::$thumbnail
```

### CODE REVIEW

**Comment by QWp6t** [comment]
I could be wrong, but I think your test should probably go in the [PostTest.php](https://github.com/jgrossi/corcel/blob/master/tests/PostTest.php) file and you should probably just use the `Post` class instead of `Page`.

**Comment by jgrossi** [comment]
Hi @manogi! Thanks for the PR. Something is wrong, because the tests didn't pass https://travis-ci.org/jgrossi/corcel/builds/131671609.

**Comment by QWp6t** [comment]
Hey @jgrossi,

That's the point of this PR. He's submitting a failing test that illustrates a bug in Corcel.

Hope that helps explain what's going on. Let me know if there's anything I can do to help resolve the issue since I'm having the same problem on my end.

**Comment by manogi** [comment]
@jgrossi yep, what is not passing travis ci is exactly the test I wrote that's failing.

**Comment by jgrossi** [comment]
Hum ok! ;-) @rundef told in #151 that Laravel has changed how to get relations. Now the right way is `$post->thumbnail()` and not `$post->thumbnail` how Corcel does. Is this correct @rundef?

**Comment by manogi** [comment]
I wrote a new Test in  PostTest.php:

````
 public function testPostIsArrayable()
    {
        $post = Post::find(1)->toArray();
        $this->assertTrue(is_array($post));
    }
```
which returns the same error. @jgrossi I think you need to take over from here and rewrite src/Post.php, as I don't have the insight what needs to be changed and where.

**Comment by rundef** [comment]
@jgrossi actually no, laravel hasn't changed how to get relation ; I think the quick and easy fix would be to reference all the relations such as **$model->relation()**.  But I think the main issue is that something is broken in our Post's **__isset** and/or **__get** method.

I'd like to help more, but I can't right now.

**Pull request merged**
